-- All timestamps are generated by the database clock (now() / clock_timestamp()).
-- Amounts are integer millilitres.

CREATE TABLE IF NOT EXISTS batches (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    total_ml      INTEGER NOT NULL,
    available_ml  INTEGER NOT NULL,
    reserved_ml   INTEGER NOT NULL,
    confirmed_ml  INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT batches_total_positive       CHECK (total_ml > 0),
    CONSTRAINT buckets_non_negative         CHECK (available_ml >= 0
                                                   AND reserved_ml >= 0
                                                   AND confirmed_ml >= 0),
    -- The accounting invariant that every transaction must preserve.
    CONSTRAINT buckets_conserve_total       CHECK (
        total_ml = available_ml + reserved_ml + confirmed_ml
    )
);

-- total_ml is immutable once a batch exists.
CREATE OR REPLACE FUNCTION batches_total_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.total_ml IS DISTINCT FROM OLD.total_ml THEN
        RAISE EXCEPTION 'total_ml of batch % is immutable', OLD.id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_batches_total_immutable ON batches;
CREATE TRIGGER trg_batches_total_immutable
    BEFORE UPDATE OF total_ml ON batches
    FOR EACH ROW
    EXECUTE FUNCTION batches_total_immutable();

-- status lifecycle: held -> confirmed | cancelled | expired (terminal)
CREATE TABLE IF NOT EXISTS reservations (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
    amount_ml     INTEGER NOT NULL,
    status        TEXT NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_at  TIMESTAMPTZ,
    cancelled_at  TIMESTAMPTZ,
    settled_at    TIMESTAMPTZ,

    CONSTRAINT reservations_amount_positive CHECK (amount_ml > 0),
    CONSTRAINT reservations_status_valid    CHECK (
        status IN ('held', 'confirmed', 'cancelled', 'expired')
    ),
    CONSTRAINT reservations_lease_positive  CHECK (expires_at > created_at),
    CONSTRAINT reservations_terminal_timestamps CHECK (
        (status <> 'confirmed' OR confirmed_at IS NOT NULL)
        AND (status <> 'cancelled' OR cancelled_at IS NOT NULL)
        AND (status <> 'expired'   OR settled_at  IS NOT NULL)
    )
);

-- Settlement hot path: held reservations of one batch past their deadline.
CREATE INDEX IF NOT EXISTS idx_reservations_batch_status_expires
    ON reservations (batch_id, status, expires_at);

CREATE INDEX IF NOT EXISTS idx_reservations_batch
    ON reservations (batch_id);
